// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfLyeyDVuBpLmFyyrYs1I1fZZ6VUAADI',
    appId: '1:348239434441:android:571a38e4e5dc3b10327318',
    messagingSenderId: '348239434441',
    projectId: 'synvmss',
    storageBucket: 'synvmss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfydtzoCDzVGqWjecNpKwF1C2MNyPq5ek',
    appId: '1:348239434441:ios:049202c27765faaa327318',
    messagingSenderId: '348239434441',
    projectId: 'synvmss',
    storageBucket: 'synvmss.firebasestorage.app',
    iosBundleId: 'com.synergy.synvmss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfydtzoCDzVGqWjecNpKwF1C2MNyPq5ek',
    appId: '1:348239434441:ios:986eb9d26ea73728327318',
    messagingSenderId: '348239434441',
    projectId: 'synvmss',
    storageBucket: 'synvmss.firebasestorage.app',
    iosBundleId: 'com.example.puri',
  );

}